# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create!(
  [
    {
      name_first: "Taro",
      name_last: "Test",
      name_user: "Taro(Local1)",
      gender: "man",
      type_user: 1,
      birthday: "20000101",
      nationality: "Japanese",
      country: "Japan",
      language_first: "Japanese",
      language_second: "English",
      language_third: "French",
      picture_profile:  "",
      picture_background: "",
      hobby:  "Sport, Traveling, Dance",
      introduction: "Hello, everyone. I'm always happy to support you with traveling Japan. Do not hesitate to message me",
      status_user: 0,
      email: "test1@gmail.com",
      password:  "111111",
    },
    {
      name_first: "Jiro",
      name_last: "Test",
      name_user: "Jiro(Local2)",
      gender: "man",
      type_user: 1,
      birthday: "20000101",
      nationality: "Japanese",
      country: "Japan",
      language_first: "Japanese",
      language_second: "English",
      language_third: "French",
      picture_profile:  "",
      picture_background: "",
      hobby:  "Sport, Traveling, Dance",
      introduction: "Hello, everyone. I'm always happy to support you with traveling Japan. Do not hesitate to message me",
      status_user: 0,
      email: "test2@gmail.com",
      password:  "222222",
    },
    {
      name_first: "Saburo",
      name_last: "Test",
      name_user: "Saburo(Local3)",
      gender: "man",
      type_user: 1,
      birthday: "20000101",
      nationality: "Japanese",
      country: "Japan",
      language_first: "Japanese",
      language_second: "English",
      language_third: "Chinese",
      picture_profile:  "",
      picture_background: "",
      hobby:  "Sport, Traveling, Dance",
      introduction: "Hello, everyone. I'm always happy to support you with traveling Japan. Do not hesitate to message me",
      status_user: 0,
      email: "test3@gmail.com",
      password:  "333333",
    },
    {
      name_first: "Shiro",
      name_last: "Test",
      name_user: "Shiro(Local4)",
      gender: "man",
      type_user: 1,
      birthday: "20000101",
      nationality: "Japanese",
      country: "Japan",
      language_first: "Japanese",
      language_second: "French",
      language_third: "",
      picture_profile:  "",
      picture_background: "",
      hobby:  "Sport, Traveling, Dance",
      introduction: "Hello, everyone. I'm always happy to support you with traveling Japan. Do not hesitate to message me",
      status_user: 0,
      email: "test4@gmail.com",
      password:  "444444",
    },
    {
      name_first: "Hanako",
      name_last: "Test",
      name_user: "Hanako(Local5)",
      gender: "woman",
      type_user: 1,
      birthday: "20000101",
      nationality: "Japanese",
      country: "Japan",
      language_first: "Japanese",
      language_second: "English",
      language_third: "",
      picture_profile:  "",
      picture_background: "",
      hobby:  "Sport, Traveling, Dance",
      introduction: "Hello, everyone. I'm always happy to support you with traveling Japan. Do not hesitate to message me",
      status_user: 0,
      email: "test5@gmail.com",
      password:  "555555",
    },
    {
      name_first: "Yoshiko",
      name_last: "Test",
      name_user: "Yoshiko(Local6)",
      gender: "man",
      type_user: 1,
      birthday: "20000101",
      nationality: "Japanese",
      country: "Japan",
      language_first: "Japanese",
      language_second: "French",
      language_third: "",
      picture_profile:  "",
      picture_background: "",
      hobby:  "Sport, Traveling, Dance",
      introduction: "Hello, everyone. I'm always happy to support you with traveling Japan. Do not hesitate to message me",
      status_user: 0,
      email: "test6@gmail.com",
      password:  "666666",
    },
    {
      name_first: "Arthur",
      name_last: "Stewart",
      name_user: "Arthur(traveler1)",
      gender: "man",
      type_user: 0,
      birthday: "20000101",
      nationality: "American",
      country: "America",
      language_first: "English",
      language_second: "Japanese",
      language_third: "",
      picture_profile:  "",
      picture_background: "",
      hobby:  "singing & creating songs",
      introduction: "Hello, everyone. I'm a professional singer. I'm excited everytime I visit Japan",
      status_user: 0,
      email: "test7@gmail.com",
      password:  "777777",
    },
    {
      name_first: "Walter",
      name_last: "Stewart",
      name_user: "Walter(traveler2)",
      gender: "man",
      type_user: 0,
      birthday: "20000101",
      nationality: "American",
      country: "America",
      language_first: "English",
      language_second: "Japanese",
      language_third: "French",
      picture_profile:  "",
      picture_background: "",
      hobby:  "singing & creating songs",
      introduction: "Hello, everyone. I'm a professional singer. I'm excited everytime I visit Japan",
      status_user: 0,
      email: "test8@gmail.com",
      password:  "888888",
    },
    {
      name_first: "Edwin",
      name_last: "Stewart",
      name_user: "Edwin(traveler3)",
      gender: "man",
      type_user: 0,
      birthday: "20000101",
      nationality: "Chinese",
      country: "China",
      language_first: "Chinese",
      language_second: "Japanese",
      language_third: "English",
      picture_profile:  "",
      picture_background: "",
      hobby:  "singing & creating songs",
      introduction: "Hello, everyone. I'm a professional singer. I'm excited everytime I visit Japan",
      status_user: 0,
      email: "test9@gmail.com",
      password:  "999999",
    },
    {
      name_first: "Owen",
      name_last: "Stewart",
      name_user: "Owen(traveler4)",
      gender: "man",
      type_user: 0,
      birthday: "20000101",
      nationality: "American",
      country: "America",
      language_first: "English",
      language_second: "Japanese",
      language_third: "",
      picture_profile:  "",
      picture_background: "",
      hobby:  "singing & creating songs",
      introduction: "Hello, everyone. I'm a professional singer. I'm excited everytime I visit Japan",
      status_user: 0,
      email: "test10@gmail.com",
      password:  "10101010",
    },
    {
      name_first: "Amy",
      name_last: "Stewart",
      name_user: "Amy(traveler5)",
      gender: "woman",
      type_user: 0,
      birthday: "20000101",
      nationality: "American",
      country: "America",
      language_first: "English",
      language_second: "Japanese",
      language_third: "",
      picture_profile:  "",
      picture_background: "",
      hobby:  "singing & creating songs",
      introduction: "Hello, everyone. I'm a professional singer. I'm excited everytime I visit Japan",
      status_user: 0,
      email: "test11@gmail.com",
      password:  "11111111",
    },
    {
      name_first: "Emma",
      name_last: "Stewart",
      name_user: "Emma(traveler6)",
      gender: "woman",
      type_user: 0,
      birthday: "20000101",
      nationality: "American",
      country: "America",
      language_first: "English",
      language_second: "Japanese",
      language_third: "",
      picture_profile:  "",
      picture_background: "",
      hobby:  "singing & creating songs",
      introduction: "Hello, everyone. I'm a professional singer. I'm excited everytime I visit Japan",
      status_user: 0,
      email: "test12@gmail.com",
      password:  "12121212",
    }
  ]
)

Post.create!(
  [
    {
      title: "Shibuya scramble crossing",
      content: "Next year, in 2020, I and my friends are gonna visit Japan and I would love to take picture of Shibuya crossing. How can I get there?",
      post_image: "",
      user_id: "7",
      area: "Kanto(Tokyo area)/関東",
      season: "N/A",
      interest: "entrainment",
      time_todo: "In 2020",
      place_todo: "Shibuya",
      status_accomplishment: 0,
      status_display: 0,
      comment_accomplishment: "",
      image_accomplishment:  "",
    },
    {
      title: "Climbing up to the top of Mt.Fuji",
      content: "I'm planning to visit Japan August next year. I love mountain climbinb, and since I visit Japan I would like to try Mt.Fuji. Is it possible to climb up Mt.Fuji on August, and if so How should I prepare for it?",
      post_image: "",
      user_id: "8",
      area: "Chubu/中部",
      season: "Summer",
      interest: "outdoor",
      time_todo: "August in 2020",
      place_todo: "Mt.Fuji",
      status_accomplishment: 0,
      status_display: 0,
      comment_accomplishment: "",
      image_accomplishment:  "",
    },
    {
      title: "Any Sushi restaurant to recommend in Tokyo",
      content: "I'm visiting Tokyo now, and I'm looking for Sushi restaurant? I would love to have casual lunch. Any recommendation?",
      post_image: "",
      user_id: "9",
      area: "Kanto(Tokyo area)/関東",
      season: "N/A",
      interest: "food",
      time_todo: "December(now)",
      place_todo: "Tokyo",
      status_accomplishment: 0,
      status_display: 0,
      comment_accomplishment: "",
      image_accomplishment:  "",
    },
    {
      title: "Summer festival and Firework",
      content: "Hello, everyone!! I'm gonna visit Japan by myself next year, and this is my first time visit to Japan. Does anyone want to see firework with me? And also I would appreciate if you recommend me summer festival & firework places.",
      post_image: "",
      user_id: "10",
      area: "N/A",
      season: "summer",
      interest: "festival",
      time_todo: "7/30-8/15",
      place_todo: "anywhere",
      status_accomplishment: 0,
      status_display: 0,
      comment_accomplishment: "",
      image_accomplishment:  "",
    },
    {
      title: "Delicious Green Tea",
      content: "I'm into Green Tea since I visited Japan last year. I don't have any plan to visit Japan, but I wanna order it through a website. Do you have any green tea product or maker you recommend? ",
      post_image: "",
      user_id: "11",
      area: "N/A",
      season: "N/A",
      interest: "food",
      time_todo: "anytime",
      place_todo: "anywhere",
      status_accomplishment: 0,
      status_display: 0,
      comment_accomplishment: "",
      image_accomplishment:  "",
    },
    {
      title: "Japanese Izakaya",
      content: "Now I'm visiting Japan, and I would love to experience Japanese Izakaya and have a amazing time with Japanese people. Do you have any recommendation?",
      post_image: "",
      user_id: "12",
      area: "Kansai(Osaka area)/関西",
      season: "N/A",
      interest: "food",
      time_todo: "December(now)",
      place_todo: "Osaka",
      status_accomplishment: 0,
      status_display: 0,
      comment_accomplishment: "",
      image_accomplishment:  "",
    },
  ]
)

Admin.create!(
  [
    {
      email: "admin@example.jp",
      password:  "1111111",
    }
  ]
)
