# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create!(
  [
    {
      name_first: "Masaya",
      name_last: "Kaneko",
      name_user: "1番のユーザ(local)",
      gender: "man",
	    type_user: 1,
      birthday: "19910713",
      nationality: "Japanese",
      country: "Japan",
      language_first: "Japanese",
      language_second: "English",
      language_third: "Korea",
      picture_profile:  "",
      picture_background: "",
      hobby:  "1 Awa-odori(Japanese traditional dance), travel",
      introduction: "1 Hello, everyone. I'm always happy to support you. Do not hegitate to message me",
      status_user: 0,
      delete_flag: "0",
      email: "test1@gmail.com",
      password:  "111111",
    },
    {
      name_first: "Masaya2",
      name_last: "Kaneko2",
      name_user: "2番のユーザ(local)",
      gender: "man",
      type_user: 1,
      birthday: "19910713",
      nationality: "Japanese",
      country: "Japan",
      language_first: "Japanese",
      language_second: "French",
      language_third: "Italian",
      picture_profile:  "",
      picture_background: "",
      hobby:  "2 Awa-odori(Japanese traditional dance), travel",
      introduction: "2 Hello, everyone. I'm always happy to support you. Do not hegitate to message me",
      status_user: 0,
      delete_flag: "0",
      email: "test2@gmail.com",
      password:  "222222",
    },
    {
      name_first: "Alexander",
      name_last: "Stewart",
      name_user: "3番のユーザ(traveler)",
      gender: "man",
      type_user: 0,
      birthday: "20000101",
      nationality: "American",
      country: "America",
      language_first: "Japanese",
      language_second: "English",
      language_third: "",
      picture_profile:  "",
      picture_background: "",
      hobby:  "3 singing & creating songs",
      introduction: "3 Hello, everyone. I'm a professional singer. I'm excited everytime I visit Japan",
      status_user: 0,
      delete_flag: "0",
      email: "test3@gmail.com",
      password:  "333333",
    },
    {
      name_first: "Alexander",
      name_last: "Stewart",
      name_user: "4番のユーザ(traveler)",
      gender: "man",
      type_user: 0,
      birthday: "20000101",
      nationality: "American",
      country: "America",
      language_first: "Italian",
      language_second: "English",
      language_third: "",
      picture_profile:  "",
      picture_background: "",
      hobby:  "4 singing & creating songs",
      introduction: "4 Hello, everyone. I'm a professional singer. I'm excited everytime I visit Japan",
      status_user: 0,
      delete_flag: "0",
      email: "test4@gmail.com",
      password:  "444444",
    },
    {
      name_first: "Alexander",
      name_last: "Stewart",
      name_user: "5番のユーザ(traveler)",
      gender: "man",
	    type_user: 0,
      birthday: "20000101",
      nationality: "American",
      country: "America",
      language_first: "English",
      language_second: "French",
      language_third: "",
      picture_profile:  "",
      picture_background: "",
      hobby:  "5 singing & creating songs",
      introduction: "5 Hello, everyone. I'm a professional singer. I'm excited everytime I visit Japan",
      status_user: 0,
      delete_flag: "0",
      email: "test5@gmail.com",
      password:  "555555",
    }
  ]
)

Post.create!(
  [
    {
      title: "1投稿 - 3ユーザ traveling to Yakushima",
      content: "Next year, in 2020, I and my friends would love to visit Yakushima, and hike in nature. Do you have any recommendation?",
      post_image: "",
	    user_id: "3",
      area: "Kyushu",
      season: "Automn",
      interest: "nature",
      time_todo: "In 2020",
      place_todo: "Yakushima",
      status_accomplishment: 0,
      status_display: 0,
      delete_flag:  "0",
      comment_accomplishment: "",
      image_accomplishment:  "",
    },
    {
      title: "2投稿 - 3ユーザ any restaurant to recommend in Tokyo",
      content: "I've been traveling around Tokyo for 2 weeks and tomorrow is the last day to stay in Japan. Do you have any idea for the last dinner?",
      post_image: "",
	    user_id: "3",
      area: "Kansai",
      season: "Summer",
      interest: "food",
      time_todo: "tomorrow",
      place_todo: "Tokyo",
      status_accomplishment: 0,
      status_display: 0,
      delete_flag:  "0",
      comment_accomplishment: "",
      image_accomplishment:  "",
    },
    {
      title: "3投稿 - 4ユーザ traveling to Yakushima",
      content: "Next year, in 2020, I and my friends would love to visit Yakushima, and hike in nature. Do you have any recommendation?",
      post_image: "",
      user_id: "4",
      area: "Kyushu",
      season: "Automn",
      interest: "nature",
      time_todo: "In 2020",
      place_todo: "Yakushima",
      status_accomplishment: 0,
      status_display: 0,
      delete_flag:  "0",
      comment_accomplishment: "",
      image_accomplishment:  "",
    },
    {
      title: "4投稿 - 5ユーザ any restaurant to recommend in Tokyo",
      content: "I've been traveling around Tokyo for 2 weeks and tomorrow is the last day to stay in Japan. Do you have any idea for the last dinner?",
      post_image: "",
      user_id: "5",
      area: "Kyushu",
      season: "winter",
      interest: "entertainment",
      time_todo: "tomorrow",
      place_todo: "Tokyo",
      status_accomplishment: 0,
      status_display: 0,
      delete_flag:  "0",
      comment_accomplishment: "",
      image_accomplishment:  "",
    },
    {
      title: "5投稿 - 5ユーザ When is Amine event held",
      content: "I've been traveling around Tokyo for 2 weeks and tomorrow is the last day to stay in Japan. Do you have any idea for the last dinner?",
      post_image: "",
      user_id: "5",
      area: "Kansai",
      season: "Summer",
      interest: "food",
      time_todo: "tomorrow",
      place_todo: "Tokyo",
      status_accomplishment: 0,
      status_display: 0,
      delete_flag:  "0",
      comment_accomplishment: "",
      image_accomplishment:  "",
    },
  ]
)

Admin.create!(
  [
    {
      email: "admin@example.jp",
      password:  "1111111",
    }
  ]
)





